---
- debug:
    var: instances.results

- name: debug output
  debug:
    msg: "{{ item.item.pod_name }}"
  with_items: "{{ instances.results }}"

- name: Generate student inventories
  template:
    src: instances.txt.j2
    dest: ./{{ item.username }}-instances.txt
  with_items: "{{ users }}"
  tags:
    - inventory
    - users
    - user_accounts

- name: Generate instructor inventory
  template:
    src: instructor_inventory.j2
    dest: ./instructor_inventory.txt
  tags:
    - inventory
    - users
    - user_accounts

- name: Generate html page with student details
  template:
    src: index.html.j2
    dest: ./index.html
  tags:
    - inventory
    - users
    - user_accounts